version: '3.8'

services:
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run serve"
    expose:
      - 3000
    depends_on:
      - backend

  backend:
    image: node:16
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/toucandb
    command: sh -c "npm install --legacy-peer-deps && npm run start"
    expose:
      - 5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ToucanDbAdmin
      MONGO_INITDB_ROOT_PASSWORD: ToucanDbAdminPWD987

volumes:
  mongo-data:
